services:
  elasticsearch:
    build:
      context: .
      dockerfile: .docker/Dockerfile.elastic
    container_name: Elasticsearch
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: Kibana
    ports:
      - "5601:5601"
    networks:
      - elastic

  database:
    container_name: postgres_db
    build:
      context: .
      dockerfile: .docker/Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elastic

volumes:
  postgres_data:


networks:
  elastic:
    driver: bridge
